env:
  global:
    - GAE_SDK: /home/travis/build/incognitoorg/fem/vendors/google_appengine_1.8.6
    
language: java

before_install:
  - mkdir -p vendors
  - pwd
  - ls -l
  - wget https://console.developers.google.com/m/cloudstorage/b/appengine-sdks/o/deprecated/186/google_appengine_1.8.6.zip  -nv
  - jar -xvf google_appengine_1.8.6.zip  
  - ls -l /home/travis/build/incognitoorg/fem/vendors
  - ls -l /home/travis/build/incognitoorg/fem
  
  
before_script:
  - node -v
  - npm -v
  - npm install -g grunt-cli
  - npm install
  - grunt -version
 
#script : "grunt onlyupload"